# Generated by Django 2.1.1 on 2018-11-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route', models.CharField(max_length=50)),
                ('Speed', models.IntegerField(default=170)),
                ('Date', models.DateField(null=True)),
                ('Vehiclenum', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route', models.CharField(max_length=50)),
                ('Density', models.IntegerField(default=170)),
                ('Date', models.DateField(null=True)),
            ],
        ),
    ]
